name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-markdown:
    environment:
      name: production
      url: https://github.com/njiticc/awesome-nicc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: make install
      # - run: make awesome_lint TODO: Fix this for NICC.
      - run: make export_markdown
      - run: make push_markdown

  build-html:
    needs: build-markdown
    environment:
      name: production
      url: https://github.com/njiticc/awesome-nicc
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: make install
      # - run: make awesome_lint TODO: Fix this for NICC.
      - run: make export_html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./html/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
