name: Check Dead Links

on:
  schedule:
    - cron: "22 22 1 * *"
  workflow_dispatch:

concurrency:
  group: check-dead-links-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-dead-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: make url_check
