name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make install
      - run: make awesome_lint
      - run: make export_markdown
      - run: make export_html
